version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - ./.db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 3s
      timeout: 3s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_HOST: '${DB_HOST}'
      POSTGRES_PORT: '${DB_PORT}'
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_PORT:-5432}:5432'

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - '${REDIS_PORT:-6379}:6379'

  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    ports:
      - '${DOCKER_API_PORT:-3000}:${API_PORT:-3000}'

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file:
      - ./.env
    ports:
      - '${DOCKER_NEXT_PORT:-8080}:3000'

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ../
      o: bind
